/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.2.1/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`
    // id("org.cadixdev.licenser").version("0.6.1") // TODO We should search an alternative license plugin
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation("com.grack:nanojson:1.10")

    compileOnly("com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.3.0")
}

gradlePlugin {
    plugins {
        create("xyz.kyngs.libby.plugin") {
            id = "xyz.kyngs.libby.plugin"
            implementationClass = "xyz.kyngs.libby.plugin.LibbyGradlePlugin"
            version = project.version
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
    withJavadocJar()
}

// license { // TODO We should search an alternative license plugin as said above
//     header(rootProject.file("HEADER.txt"))
//     include("**/*.java")
// }

tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}

version = "1.2.2"
