/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.miguvt.libby.plugin;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.language.jvm.tasks.ProcessResources;

/**
 * Gradle plugin that generates a {@code libby.json} manifest of runtime dependencies.
 * <p>
 * This plugin creates a custom {@code libby} configuration and a {@code libby} task
 * that outputs dependency metadata for use with the Libby library loader.
 */
public class LibbyGradlePlugin implements Plugin<Project> {

    /** Default constructor. */
    public LibbyGradlePlugin() {
    }

    /**
     * Applies the libby plugin to the given project.
     *
     * @param project the Gradle project
     */
    public void apply(Project project) {
        project.getExtensions().create("libby", LibbyExtension.class);

        Configuration customScope = project.getConfigurations().create("libby");

        project.getPlugins().apply(JavaPlugin.class);
        project.getConfigurations().getByName(JavaPlugin.COMPILE_ONLY_CONFIGURATION_NAME).extendsFrom(customScope);

        project.getTasks().register("libby", LibbyTask.class, customScope, project);
        project.getTasks().withType(ProcessResources.class).configureEach(task -> {
            task.dependsOn("libby");
        });
    }
}
